name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  linux-unittests:
    name: 'Linux'
    strategy:
      # we disable fail-fast, as otherwise any failed job would cancel the others.
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            java: 11
          - os: ubuntu-latest
            java: 17
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '${{ matrix.java }}'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build scenery
        run: ./gradlew build -x dokkaHtml -x dokkaHtmlJar -x javadoc -x dokkaJavadocJar --no-daemon

  windows-unittests:
    name: 'Windows'
    strategy:
      # we disable fail-fast, as otherwise any failed job would cancel the others.
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            java: 11
          - os: windows-latest
            java: 17
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - name: configure Pagefile
        uses: al-cheb/configure-pagefile-action@v1.3
        with:
          minimum-size: 8GB
          maximum-size: 32GB
          disk-root: "D:"
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '${{ matrix.java }}'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Build scenery
        run: ./gradlew build -x dokkaHtml -x dokkaHtmlJar -x javadoc -x dokkaJavadocJar --no-daemon

  mac-unittests:
    name: 'macOS'
    strategy:
      # we disable fail-fast, as otherwise any failed job would cancel the others.
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            java: 11
          - os: macos-latest
            java: 17
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '${{ matrix.java }}'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build scenery
        run: ./gradlew build -x dokkaHtml -x dokkaHtmlJar -x javadoc -x dokkaJavadocJar --no-daemon
